### PR TITLE
webui: rewards ui

### PR DESCRIPTION
**Pull request by or2e**

### CODE REVIEW

**Review by Meowkov — DISMISSED** [review]
I can not judge the code but by now figure that the SeedDataCommand.cs is there for local testing.
If it impacts prod, we could already add Yeldur, James and i think Lemon to the admin group for rewards.
Else ignore me :D

Approved

**Comment by Muparadzi** [comment]
> I can not judge the code but by now figure that the SeedDataCommand.cs is there for local testing. If it impacts prod, we could already add Yeldur, James and i think Lemon to the admin group for rewards. Else ignore me :D
> 
> Approved

SeedDataCommand.cs is purely there to seed the database when one is newly generated. This should obviously only happen in test environments and will never impact prod.

**Review by Meowkov — APPROVED** [review]

**Comment by Muparadzi** [comment]
Is it possible for us to track which user has rewarded the player? Currently we can only log which user received the reward but not by whom.

**Comment by or2e** [comment]
Yeah, that's a good take

**Comment by or2e** [comment]
rdy
https://cdn.discordapp.com/attachments/680849028774232109/1246229953612087346/image.png?ex=665ba196&is=665a5016&hm=a92b56de7bf924a57f0857155c9f04e8b3dd7b419e9d1e1b23bc981d5b76fda0&

**Review by Muparadzi — APPROVED** [review]

**Review by Muparadzi — APPROVED** [review]

**Pull request merged**
