### PR TITLE
feat: personal items

### PR DESCRIPTION
**Pull request by or2e**
closed: https://github.com/namidaka/crpg/issues/13 https://github.com/namidaka/crpg/issues/35

### CODE REVIEW

**Review by Meowkov — DISMISSED** [review]
I can not help reviewing the code but you are the master of tests and I don't doubt that there is a logic error or anything.

The only thing I could question is if the entries in SeedDataCommand.cs that include items for you and takeo are leftover from tests or if those were there before and just changed now as diff is showing.
Edit: I figure the SeedDataCommand.cs only impacts testing so ignore that :D

Approved on my end.

**Review by Muparadzi — DISMISSED** [review]
Looking good!

Would we need to disable the items using the API after they are added? I don't think we support creating disabled items from the start in items.json.

**Comment by or2e** [comment]
Yeah, I also didn't write the tests
I suggest to get in touch sometime and discuss this mr.

**Comment by Muparadzi** [comment]
- There is a bug where reforging or looming a personal item will turn it into a 'normal' item
- If you are given a personal item that you have already purchased from the store, all of the items with the same item id will become personal.

Should we disable the ability to heirloom or reforge personal items? 
Will we ever reward personal items that are also available in the store?

**Comment by or2e** [comment]
> Looking good!
> 
> Would we need to disable the items using the API after they are added? I don't think we support creating disabled items from the start in items.json.

image

**Comment by or2e** [comment]
> * There is a bug where reforging or looming a personal item will turn it into a 'normal' item
> * If you are given a personal item that you have already purchased from the store, all of the items with the same item id will become personal.
> 
> Should we disable the ability to heirloom or reforge personal items? Will we ever reward personal items that are also available in the store?

1/ 
After changing the architecture (prop personal is now attached on `UserItem` entity), 1 bug was fixed.
Let there be the possibility of loom/reforege.

2/ 
I can forbid the transfer of usual items, but let it be for now.

3/ 
I think I'm left to figure out what to do when an item is rebalanced and has a id change (ex. `v2` -> `v3`).
For example, I can somehow by working [with strings and regular](https://github.com/namidaka/crpg/blob/master/src/Application/System/Commands/SeedDataCommand.cs#L2162) expressions to automatically add a new version of a personal item.

fyi: @Meowkov @MrMendo

**Review by Muparadzi — APPROVED** [review]

**Review by Meowkov — APPROVED** [review]
Looking good? :D

**Pull request merged**
