### PR TITLE
Str reqs

### PR DESCRIPTION
**Pull request by abearirlcrpg**
str reqs for weapons + shields 

bow, xbow, pole = 24 (IMO pole should be 24 to put the final nail in the agi glaive coffin but 21 would probably work too) 
everything else = 21 (maybe 2h -> 18 to enable the classic naked 2h spammer build)

### CODE REVIEW

**Comment by namidaka** [comment]
This needs consensus. Discuss with balancing team.
Second of all if it were to get accepted , the job is like 10% done.
Exporter in branch HarmonyCrafterExporter needs to be updated so the items.json have the requirements needed , then it needs to be displayed on the website.

**Comment by namidaka** [comment]
Also as is you change has no impact whatsoever.
You need to implement the consequences of being underrequirement in AgentStatCalculationModel. 
If i were to merge this as is , literally nothing would change in the game

**Comment by abearirlcrpg** [comment]
> Also as is you change has no impact whatsoever. You need to implement the consequences of being underrequirement in AgentStatCalculationModel. If i were to merge this as is , literally nothing would change in the game

didnt realize it was only done for crossbows, i saw a reference to item reqs somewhere else and assumed it was universal ill revise and resubmit

**Comment by namidaka** [comment]
Don't forget that part
"This needs consensus. Discuss with balancing team."
It's a massive change , and it won't get accepted if you don't garner enough support

**Comment by Yeldur** [comment]
Team is lead by myself alongside a few others; I'll raise the discussion with them and will come back to you once I've gathered some more info/details

**Comment by Yeldur** [comment]
Okay, so I've spoken to the team about this and here's the long and short:

1) Thus far, there's been a repeated theme that proponents of STR Reqs haven't provided **convincing, _factual_ arguments** demonstrating that STR Reqs would **resolve specific gameplay issues or imbalances**.

2) The current dominance of STR based builds in cRPG seems to indicate that adding STR reqs would be unnecessary, because STR dominates the META. Introducing STR reqs for weapons without a compelling reason could unjustly penalize AGI-focused builds, exacerbating the existing imbalance between the two build types. It's worth noting that there is a BIG difference between a **high level build** and a **low level build** - And 99% of the time, high level "agi" builds are where problems are being seen. In other words, this isn't a problem of AGI, but of Level.

3) Existing mechanisms relating to STR already exist, weight & weapon length. If you are low STR, you have less weapon length, if you are low STR, you have less weight (armour/gear in general) - Where these problems are mitigated is again, as a result of **high level** builds, meaning the problem is again, not with AGI, but with levels.

If you were inclined to push support for STR reqs, you'd need to **properly** address at the very least these three points. 

For 1) you'd need to come equipped with evidence demonstrating how STR Reqs would resolve specific gameplay issues/imbalances.

For 2) you'd need to show how STR reqs would affect players across different levels, especially focusing on high-level AGI builds that will not be impacted by these STR reqs, among other things.

For 3) you'd need to work out why these mechanisms **are not** solving the problem and then work out how STR reqs **would**

**Pull request closed without merging**
