### PR TITLE
webui: Help page for new players

### PR DESCRIPTION
**Pull request by Yeldur**
Create a temporary help page for new players

This change adds a Help Page into the already built-in help icon on the website containing a hub of information for a new player to utilise.

Eventually this can be scrapped in favour of Onboarding, however for the interim period having this in place whilst Onboarding is being looked into, this PR serves as a way to do this by adding four tabs:

1) Overview - General welcome info to the Help Hub
2) Build Support - Provides fundamentals for Building your character in cRPG and teaches commonly used terminology
3) Joining a Clan - Provides user with information on joining clans and why it is beneficial
4) FAQ - Frequently asked questions by new players.
(All pages contain a footer directing the users to Discord to promote our community)

<details>
  <summary>Screenshots</summary>
 
image
image
image
image
</details>

### CODE REVIEW

**Comment by Yeldur** [comment]
(also yes orle i plan to look into onboarding too! this is just a stopgap :D)

**Review by Muparadzi — CHANGES_REQUESTED** [review]
Needs CN and RU localisation ideally

**Comment by Yeldur** [comment]
Damn! I knew I would forget about this. I will get it sorted ASAP and update

**Comment by Yeldur** [comment]
have added RU and CN localisation in advance of orle looking to add his own changes to this, will hopefully make things easier for him :D

**Comment by namidaka** [comment]
will merge once @or2e  reviews it

**Review by or2e — APPROVED** [review]

**Comment by or2e** [comment]
I didn't translate into Chinese as there are a lot of subtleties and I don't want to trust auto-translation. 
Maybe later someone from the community will want to do the translation

**Comment by Yeldur** [comment]
> I didn't translate into Chinese as there are a lot of subtleties and I don't want to trust auto-translation. Maybe later someone from the community will want to do the translation

I'll run my translation past kaikaikai, he can usually validate if it is OK, if so, i will update

**Comment by or2e** [comment]
rdy to merge

**Review by Meowkov — APPROVED** [review]
Approved

**Review by Muparadzi — APPROVED** [review]

**Pull request merged**
